<?php

return [

    'products' => [

        [
            'name' => 'Vino Rosso di Sicilia',
            'weight'=> '1000 ml',
            'price' => 12.00,
            'image_url' => 'https://www.prodottiesaporidisicilia.it/cdn/shop/products/ciuridistrata_800x800.png?v=1631865823',
            'quantity' => 50,
            'category' => 'Vini',
        ],
        [
            'name' => 'Vino Bianco di Sicilia',
            'weight'=> '1000 ml',
            'price' => 12.00,
            'image_url' => 'https://shared.winelivery.com/images/products/63f5fb6a20ee18006d5510a9.jpeg',
            'quantity' => 50,
            'category' => 'Vini',
        ],
        [
            'name' => 'Vino Rosso di Catania',
            'weight'=> '1000 ml',
            'price' => 11.50,
            'image_url' => 'https://www.rosadivini.com/wp-content/uploads/2021/12/rosso-di-laura-fronte-720x720.jpg',
            'quantity' => 50,
            'category' => 'Vini',
        ],
        [
            'name' => 'Vino Rosso di Palermo',
            'weight'=> '1000 ml',
            'price' => 12.50,
            'image_url' => 'https://www.goccedisicilia.com/3380/bayamore-red-wine-2021-doc-sicilia-firriato.jpg',
            'quantity' => 50,
            'category' => 'Vini',
        ],
        [
            'name' => 'Vino Bianco di Agrigento',
            'weight'=> '1000 ml',
            'price' => 16.00,
            'image_url' => 'https://shop.rivoldrink.it/wp-content/uploads/2023/04/Donna_Fugata_Anthilia.jpg',
            'quantity' => 50,
            'category' => 'Vini',
        ],
        [
            'name' => 'Miele Millefiori',
            'weight'=> '500 gr',
            'price' => 8.50,
            'image_url' => 'https://sicil-store.com/2083-medium_default/miele-di-millefiori-bio-segreti-di-sicilia-gr250.jpg',
            'quantity' => 30,
            'category' => 'Miele',
        ],
        [
            'name' => 'Miele Castagno',
            'weight'=> '500 gr',
            'price' => 7.50,
            'image_url' => 'https://www.goccedisicilia.com/4533-large_default/miele-di-castagno-di-ape-nera-siciliana-400-g-slow-food.jpg',
            'quantity' => 30,
            'category' => 'Miele',
        ],
        [
            'name' => 'Miele Eucalipto',
            'weight'=> '500 gr',
            'price' => 9.50,
            'image_url' => 'https://www.essenzedisicilia.it/1009-large_default/miele-biologico-eucalipto.jpg',
            'quantity' => 30,
            'category' => 'Miele',
        ],
        [
            'name' => 'Miele Girasole',
            'weight'=> '500 gr',
            'price' => 8.50,
            'image_url' => 'https://m.media-amazon.com/images/I/71KO1Xk2ncL._AC_UF350,350_QL80_.jpg',
            'quantity' => 30,
            'category' => 'Miele',
        ],
        [
            'name' => 'Miele Melata',
            'weight'=> '500 gr',
            'price' => 8.50,
            'image_url' => 'https://www.cantineprivitera.com/wp-content/uploads/2018/11/miele-melata-500.png',
            'quantity' => 30,
            'category' => 'Miele',
        ],
        [
            'name' => 'Crema al Pistacchio di Modica',
            'weight'=> '250 gr',
            'price' => 5.50,
            'image_url' => 'https://shop.sartoriadelgusto.com/wp-content/uploads/2021/06/DOLCEZZE-crema-pistacchio.jpg',
            'quantity' => 20,
            'category' => 'Crema al Pistacchio',
        ],
        [
            'name' => 'Crema al Pistacchio di Marsala',
            'weight'=> '250 gr',
            'price' => 5.00,
            'image_url' => 'https://www.bronte.store/wp-content/uploads/2018/08/crema-di-pistacchio-pistace-bronte-store-190g-wpp1632747247966.jpg',
            'quantity' => 20,
            'category' => 'Crema al Pistacchio',
        ],
        [
            'name' => 'Crema al Pistacchio di Letojanni',
            'weight'=> '250 gr',
            'price' => 4.50,
            'image_url' => 'https://www.saporelite.com/wp-content/uploads/2021/07/Crema-di-pistacchi-Antichi-Sapori-dellEtna-Creme-spalmabili-Fronte.jpg',
            'quantity' => 20,
            'category' => 'Crema al Pistacchio',
        ],
        [
            'name' => 'Crema al Pistacchio di Taormina',
            'weight'=> '250 gr',
            'price' => 7.00,
            'image_url' => 'https://m.media-amazon.com/images/I/61WS8wYja7L.jpg',
            'quantity' => 20,
            'category' => 'Crema al Pistacchio',
        ],
        [
            'name' => 'Crema al Pistacchio di Mondello',
            'weight'=> '250 gr',
            'price' => 6.00,
            'image_url' => 'https://lorodelcontadino.it/wp-content/uploads/2017/04/pistacchio2-1.png',
            'quantity' => 20,
            'category' => 'Crema al Pistacchio',
        ],
        [
            'name' => 'Olio d\'oliva extravergine di Trapani',
            'weight'=> '1000 ml',
            'price' => 9.00,
            'image_url' => 'https://cdn.olico.it/5236-thickbox_default/olio-extra-vergine-di-oliva-igp-sicilia-500-ml.jpg',
            'quantity' => 40,
            'category' => 'Olio',
        ],
        [
            'name' => 'Olio d\'oliva extravergine di Noto',
            'weight'=> '1000 ml',
            'price' => 9.50,
            'image_url' => 'https://www.topfooditaly.net/wp-content/uploads/2019/12/olio-extravergine-di-oliva-igp-sicilia-la-goccia-doro.jpg',
            'quantity' => 40,
            'category' => 'Olio',
        ],
        [
            'name' => 'Olio d\'oliva extravergine di Siracusa',
            'weight'=> '1000 ml',
            'price' => 9.00,
            'image_url' => 'https://www.emporiosolidaleviterbo.it/wp-content/uploads/2020/06/olio-extravergine-oliva-dop.jpg',
            'quantity' => 40,
            'category' => 'Olio',
        ],
        [
            'name' => 'Olio d\'oliva extravergine di Castel Iudica',
            'weight'=> '1000 ml',
            'price' => 8.50,
            'image_url' => 'https://www.sicilybio.it/wp-content/uploads/2022/10/bottiglia-vetro-scaled.jpg',
            'quantity' => 40,
            'category' => 'Olio',
        ],
        [
            'name' => 'Olio d\'oliva extravergine di Regalbuto',
            'weight'=> '1000 ml',
            'price' => 10.00,
            'image_url' => 'https://www.dallasicilia.com/wp-content/uploads/Olio-Extra-Vergine-di-Oliva-Biologico-Siciliano-85467-5.png',
            'quantity' => 40,
            'category' => 'Olio',
        ],
        [
            'name' => 'Formaggio Parmigiano Reggiano di Milazzo',
            'weight'=> '300 gr',
            'price' => 15.00,
            'image_url' => 'https://shop.silvanoromaniparma.it/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/c/u/cuoreparmigiano_1.jpg',
            'quantity' => 25,
            'category' => 'Formaggi',
        ],
        [
            'name' => 'Formaggio Parmigiano Reggiano di Misterbianco',
            'weight'=> '400 gr',
            'price' => 15.50,
            'image_url' => 'https://www.caseificiodelparco.it/pub/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/u/n/un-ottavo_1.jpg',
            'quantity' => 25,
            'category' => 'Formaggi',
        ],
        [
            'name' => 'Formaggio Parmigiano Reggiano di Centuripe',
            'weight'=> '350 gr',
            'price' => 13.50,
            'image_url' => 'https://shop.silvanoromaniparma.it/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/p/a/parmigiano1.jpg',
            'quantity' => 25,
            'category' => 'Formaggi',
        ],
        [
            'name' => 'Formaggio Parmigiano Reggiano di Leonforte',
            'weight'=> '300 gr',
            'price' => 14.00,
            'image_url' => 'https://www.ferrarini.com/wp-content/uploads/2020/05/products-62289.jpg',
            'quantity' => 25,
            'category' => 'Formaggi',
        ],
        [
            'name' => 'Formaggio Parmigiano Reggiano di Nicosia',
            'weight'=> '450 gr',
            'price' => 17.00,
            'image_url' => 'https://www.ilsalumiereparma.it/323-large_default/punta-parmigiano-reggiano-dop-24-mesi-1kg.jpg',
            'quantity' => 25,
            'category' => 'Formaggi',
        ],

    ],
    [
        'name' => 'Arance di Sicilia',
        'weight'=> '400 gr',
        'price' => 12.00,
        'image_url' => 'https://www.aranceok.com/wp-content/uploads/2023/01/arance-siciliane-da-tavola.jpg',
        'quantity' => 50,
        'category' => 'Arance',
    ],
    [
        'name' => 'Arance di Nissoria',
        'weight'=> '450 gr',
        'price' => 12.50,
        'image_url' => 'https://www.arancepoggiodianaribera.it/wp-content/uploads/2022/08/arancefioroni-1-1024x1024.jpg',
        'quantity' => 50,
        'category' => 'Arance',
    ],
    [
        'name' => 'Arance di Milazzo',
        'weight'=> '350 gr',
        'price' => 11.00,
        'image_url' => 'https://www.siquri.com/2713-large_default/arance-tarocco-biologiche-sicilia.jpg',
        'quantity' => 50,
        'category' => 'Arance',
    ],
    [
        'name' => 'Arance di Floridia',
        'weight'=> '450 gr',
        'price' => 13.00,
        'image_url' => 'https://www.squisicily.it/shop/91-superlarge_default/arance-.jpg',
        'quantity' => 50,
        'category' => 'Vini',
    ],
    [
        'name' => 'Arance di Ragusa',
        'weight'=> '450 gr',
        'price' => 16.00,
        'image_url' => 'https://www.cicalia.com/it/img/imgproducts/59620/l_59620.jpg',
        'quantity' => 50,
        'category' => 'Arance',
    ],
    [
        'name' => 'Limoni di Sicilia',
        'weight'=> '400 gr',
        'price' => 13.50,
        'image_url' => 'https://www.arancepoggiodianaribera.it/wp-content/uploads/2022/08/limonidisicilia-1.jpg',
        'quantity' => 30,
        'category' => 'Limoni',
    ],
    [
        'name' => 'Limoni di Vittoria',
        'weight'=> '450 gr',
        'price' => 14.50,
        'image_url' => 'https://contradacrizzina.it/wp-content/uploads/2019/01/CC_cassa_limoni_01.jpg',
        'quantity' => 30,
        'category' => 'Limoni',
    ],
    [
        'name' => 'Limoni di Augusta',
        'weight'=> '300 gr',
        'price' => 12.50,
        'image_url' => 'https://passoladro.it/wp-content/uploads/2022/10/cassetta-limoni-bio-2-2.jpg',
        'quantity' => 30,
        'category' => 'Limoni',
    ],
    [
        'name' => 'Limoni di Troina',
        'weight'=> '250 gr',
        'price' => 10.50,
        'image_url' => 'https://sicibia.it/wp-content/uploads/2019/04/cassetta-arance-limoni-bio.jpg',
        'quantity' => 30,
        'category' => 'Limoni',
    ],
    [
        'name' => 'Limoni di Randazzo',
        'weight'=> '450 gr',
        'price' => 15.50,
        'image_url' => 'https://www.agribiojalari.it/wp-content/uploads/2021/05/cassetta_limoni-1.jpg',
        'quantity' => 30,
        'category' => 'Limoni',
    ],
];
